#!/bin/bash
# makerun.sh
# Make sure alqod is always running.
# Add the following to the crontab (i.e. crontab -e)
# */5 * * * * ~/alqonode/makerun.sh

if ps -A | grep alqod > /dev/null
then
  exit
else
  /root/ALQO/alqod &
fi
